### ISSUE TITLE
Lab 5 videos appear but don't work

### ISSUE THREAD

**Issue by AaronMill93** [ACloudGuru/serverless-workshop#15]
After a bit of debugging I noticed that in the lab 5 PDF the environment variable **S3** for lambda function **push-transcoded-url-to-firebase** should be changed to **S3_TRANSCODED_BUCKET_URL** to be consistent with index.js

Great course though, thanks!

**Comment by julianpitt** [comment]
Fixed with the commit 7e6205c4779706022b79bcadbd56afc2551b80ce
