### ISSUE TITLE
Serverless framework for deploy

### ISSUE THREAD

**Issue by sp90** [ACloudGuru/serverless-workshop#17]
Seems like a great project may I suggest a [serverless](https://serverless.com/) application so with one command its possible to deploy to lambda

**Comment by julianpitt** [comment]
Hi sp90,
We purposely don't use the serverless framework in this course so you understand how the process of uploading a function and how the data flows thorugh the whole system.
If we used a deployment framework like the serverless framework of SAMS, you wouldn't really be learning how the different serverless components fit together, we'd instead be teaching you how to use a specific framework.
